# Generated by Django 2.2 on 2019-04-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='key',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stars',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='technology',
            field=models.CharField(max_length=300, verbose_name='Технологии'),
        ),
        migrations.AlterField(
            model_name='mistake',
            name='picture',
            field=models.ImageField(upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='urls',
            field=models.CharField(max_length=1000, verbose_name='Ссылки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='Телефон'),
        ),
    ]
