# Generated by Django 2.2 on 2019-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news2',
            name='notapplicable',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='не относится'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(max_length=100, verbose_name='О себе'),
        ),
    ]
