# Generated by Django 2.2 on 2019-05-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0002_auto_20190430_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Buttons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botton1', models.CharField(default='Копка 1', max_length=100, verbose_name='Значение кнопки')),
                ('botton2', models.CharField(default='Копка 2', max_length=100, verbose_name='Значение кнопки')),
                ('botton3', models.CharField(default='Копка 3', max_length=100, verbose_name='Значение кнопки')),
                ('botton4', models.CharField(default='Копка 4', max_length=100, verbose_name='Значение кнопки')),
                ('botton5', models.CharField(default='Копка 5', max_length=100, verbose_name='Значение кнопки')),
                ('botton6', models.CharField(default='Копка 6', max_length=100, verbose_name='Значение кнопки')),
                ('botton7', models.CharField(default='Копка 7', max_length=100, verbose_name='Значение кнопки')),
                ('botton8', models.CharField(default='Копка 8', max_length=100, verbose_name='Значение кнопки')),
                ('botton9', models.CharField(default='Копка 9', max_length=100, verbose_name='Значение кнопки')),
                ('botton10', models.CharField(default='Копка 10', max_length=100, verbose_name='Значение кнопки')),
                ('botton11', models.CharField(default='Копка 11', max_length=100, verbose_name='Значение кнопки')),
                ('botton12', models.CharField(default='Копка 12', max_length=100, verbose_name='Значение кнопки')),
                ('botton13', models.CharField(default='Копка 13', max_length=100, verbose_name='Значение кнопки')),
                ('botton14', models.CharField(default='Копка 14', max_length=100, verbose_name='Значение кнопки')),
                ('botton15', models.CharField(default='Копка 15', max_length=100, verbose_name='Значение кнопки')),
                ('botton16', models.CharField(default='Копка 16', max_length=100, verbose_name='Значение кнопки')),
                ('botton17', models.CharField(default='Копка 17', max_length=100, verbose_name='Значение кнопки')),
                ('botton18', models.CharField(default='Копка 18', max_length=100, verbose_name='Значение кнопки')),
                ('botton19', models.CharField(default='Копка 19', max_length=100, verbose_name='Значение кнопки')),
                ('botton20', models.CharField(default='Копка 20', max_length=100, verbose_name='Значение кнопки')),
                ('number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_bot.Number')),
            ],
        ),
    ]
