# Generated by Django 2.2 on 2019-04-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0002_auto_20190410_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
