# Generated by Django 2.2 on 2019-04-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0004_auto_20190411_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news2',
            name='negative',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news2',
            name='neutral',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news2',
            name='positive',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
