# Generated by Django 2.2 on 2019-05-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0004_auto_20190507_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttons',
            name='num',
        ),
        migrations.AddField(
            model_name='number',
            name='button',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='first_bot.Buttons'),
            preserve_default=False,
        ),
    ]
