# Generated by Django 2.2 on 2019-04-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0005_auto_20190411_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news2',
            name='negative',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='news2',
            name='neutral',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news2',
            name='positive',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
