# Generated by Django 2.2 on 2019-05-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0005_auto_20190507_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buttons',
            old_name='botton1',
            new_name='botton',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton10',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton11',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton12',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton13',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton14',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton15',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton16',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton17',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton18',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton19',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton2',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton20',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton3',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton4',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton5',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton6',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton7',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton8',
        ),
        migrations.RemoveField(
            model_name='buttons',
            name='botton9',
        ),
    ]
