# Generated by Django 2.2 on 2019-05-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0006_auto_20190510_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='button',
        ),
        migrations.AddField(
            model_name='buttons',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
