# Generated by Django 2.2 on 2019-04-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0006_auto_20190412_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news2',
            name='negative',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='news2',
            name='neutral',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='news2',
            name='positive',
            field=models.IntegerField(default=1),
        ),
    ]
