# Generated by Django 2.2 on 2019-05-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0007_auto_20190510_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
