# Generated by Django 2.2 on 2019-04-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0008_auto_20190412_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news2',
            name='negative',
            field=models.IntegerField(blank=True, null=True, verbose_name='2 = отрицательная'),
        ),
        migrations.AlterField(
            model_name='news2',
            name='neutral',
            field=models.IntegerField(blank=True, null=True, verbose_name='3 = нейтрпльная'),
        ),
        migrations.AlterField(
            model_name='news2',
            name='positive',
            field=models.IntegerField(blank=True, null=True, verbose_name='1 = положительная'),
        ),
    ]
