# Generated by Django 2.2 on 2019-04-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0009_auto_20190412_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news2',
            name='negative',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='news2',
            name='neutral',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='news2',
            name='positive',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
