# Generated by Django 2.2 on 2019-04-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0011_auto_20190412_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
        migrations.AddField(
            model_name='news',
            name='negative',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='neutral',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='positive',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
