# Generated by Django 2.2 on 2019-04-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0012_auto_20190412_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='news',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='news',
            name='positive',
        ),
        migrations.AddField(
            model_name='news',
            name='types',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
