# Generated by Django 2.2 on 2019-04-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0013_auto_20190412_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news2',
            name='negative',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='негативная'),
        ),
        migrations.AlterField(
            model_name='news2',
            name='neutral',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='нетральная'),
        ),
        migrations.AlterField(
            model_name='news2',
            name='positive',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='позитивная'),
        ),
    ]
