# Generated by Django 2.2 on 2019-04-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0015_auto_20190417_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news2',
            name='negative',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='негативная'),
        ),
        migrations.AlterField(
            model_name='news2',
            name='neutral',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='нейтральная'),
        ),
        migrations.AlterField(
            model_name='news2',
            name='positive',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='позитвная'),
        ),
    ]
