# Generated by Django 2.2 on 2019-04-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0016_auto_20190417_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
