# Generated by Django 2.2 on 2019-04-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0017_remove_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Фото профиля'),
        ),
    ]
