# Generated by Django 2.2 on 2019-04-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0018_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='key',
        ),
    ]
