# Generated by Django 2.2 on 2019-04-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0019_remove_news_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(max_length=100, verbose_name='о себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
    ]
