# Generated by Django 2.2 on 2019-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0020_auto_20190425_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistake',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mistake',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип ошибки'),
        ),
        migrations.AlterField(
            model_name='mistake',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='mistake',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
