# Generated by Django 2.2 on 2019-04-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0022_auto_20190426_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistake',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
