# Generated by Django 2.2 on 2019-04-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0023_auto_20190426_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('body', models.TextField(verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, upload_to='images/', verbose_name='Картинка')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Зыезда',
                'verbose_name_plural': 'Звезды',
            },
        ),
        migrations.RemoveField(
            model_name='bot',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_bot.Bot'),
        ),
        migrations.DeleteModel(
            name='Stars',
        ),
        migrations.AddField(
            model_name='profile',
            name='medal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_bot.Medal'),
        ),
    ]
