# Generated by Django 2.2 on 2019-04-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0024_auto_20190426_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_bot.Bot'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_bot.Medal'),
        ),
    ]
