# Generated by Django 2.2 on 2019-04-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0025_auto_20190426_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='medal',
        ),
        migrations.AddField(
            model_name='bot',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_bot.Profile'),
        ),
        migrations.AddField(
            model_name='medal',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='first_bot.Profile'),
        ),
    ]
