# Generated by Django 2.2 on 2019-04-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_bot', '0027_auto_20190426_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medal',
            name='profile',
        ),
        migrations.AddField(
            model_name='medal',
            name='profile',
            field=models.ManyToManyField(blank=True, null=True, to='first_bot.Profile'),
        ),
    ]
